from typing import Protocol, Dict, List, Optional, Any, Tuple

# Forward declaration or placeholder for TokenMetrics if it's defined elsewhere (e.g., solgem.py or a models.py)
# This avoids circular dependencies if TokenMetrics itself uses some of these protocols.
class TokenMetrics(Protocol):
    address: str
    name: str
    symbol: str
    # ... other essential fields from TokenMetrics dataclass ...

class DexScreenerAPIProtocol(Protocol):
    async def get_solana_pairs(self) -> List[Dict[str, Any]]: ...
    async def get_pair_details(self, pair_address: str) -> Optional[Dict[str, Any]]: ...
    async def get_token_info(self, token_addresses: List[str]) -> List[Dict[str, Any]]: ...
    async def get_token_history(self, token_address: str, limit: Optional[int] = None, resolution: Optional[str] = None) -> List[Dict[str, Any]]: ...

class SolscanAPIProtocol(Protocol):
    async def get_token_holders(self, token_address: str) -> int: ...
    async def get_whale_holdings(self, token_address: str) -> Dict[str, float]: ...
    # Add other methods if SolscanAPI has more that are used by services

class JupiterAPIProtocol(Protocol):
    async def get_token_price_usd(self, token_mint: str) -> Optional[float]: ...
    async def get_token_list(self) -> List[Dict[str, Any]]: ...
    async def get_historical_prices(self, token_mint: str, timeframe: str, limit: int) -> Optional[List[Dict[str, Any]]]: ...
    async def get_historical_volume(self, token_mint: str, timeframe: str, limit: int) -> Optional[List[Dict[str, Any]]]: ...
    async def close(self) -> None: ...

class HeliusAPIProtocol(Protocol):
    async def get_token_metadata(self, token_addresses: List[str]) -> Dict[str, Any]: ...
    async def get_current_holder_count(self, token_mint: str) -> Optional[int]: ...
    async def get_historical_holder_counts(self, token_mint: str, timeframes: List[str]) -> Dict[str, Optional[int]]: ...
    async def get_transaction_count_for_token(self, token_mint: str, lookback_seconds: int) -> Optional[int]: ...
    async def close_session(self) -> None: ... # if helius_api manages a session

class SolanaRPCProtocol(Protocol): # Covers both SolanaRPC and EnhancedSolanaRPC methods used by services
    async def get_token_supply_details(self, token_address: str) -> Optional[Dict[str, Any]]: ... # Example method for EnhancedSolanaRPC
    # Add other common RPC methods like get_account_info, get_signature_history etc. if directly used by services needing this protocol.
    # For now, focusing on what TokenEnrichmentService might directly use from an RPC like object.

class DatabaseManagerProtocol(Protocol):
    async def save_token(self, metrics: TokenMetrics, score: float) -> None: ...
    # Add other DB interaction methods used by services, e.g., for whale tracking persistence
    async def update_whale_in_db(self, token_address: str, whale_data: Any) -> None: ... # Define 'Any' more specifically if possible (e.g. WhaleWallet model)

class TelegramAlerterProtocol(Protocol):
    async def send_gem_alert(self, metrics: TokenMetrics, score: float, score_breakdown: Dict, enhanced_data: Dict, pair_address: Optional[str]) -> None: ...
    async def send_message(self, message: str) -> None: ...

class GemScorerProtocol(Protocol):
    def calculate_score(self, metrics: TokenMetrics, historical_data: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]: ...

class TrendAnalysisServiceProtocol(Protocol):
    def analyze_volume_trend(self, pair_address: str) -> Dict[str, Any]: ...
    def analyze_transaction_trend(self, pair_data: Dict[str, Any]) -> Dict[str, Any]: ...

class FilteringServiceProtocol(Protocol):
    async def is_potential_gem(self, pair: Dict[str, Any]) -> bool: ...
    async def apply_dexscreener_filters_async(self, dexscreener_pair_data: Dict[str, Any], token_address: Optional[str] = None) -> List[str]: ...
    # _calculate_price_changes_with_jupiter_async is internal, may not need to be in protocol unless used elsewhere.

class TokenEnrichmentServiceProtocol(Protocol):
    async def analyze_token_comprehensively(self, pair_data: Dict[str, Any]) -> Optional[TokenMetrics]: ...

class MomentumAnalyzerProtocol(Protocol):
     async def analyze_token_momentum(self, token_address: str) -> Dict[str, Any]: ...

class EnhancedScoringProtocol(Protocol):
    async def enhance_token_analysis(self, token_address: str, token_data: Dict[str, Any], base_score: float) -> Dict[str, Any]: ...
    def calculate_enhanced_gem_score(self, base_score: float, enhanced_data: Dict[str, Any]) -> Tuple[float, Dict[str, Any]]: ...
    async def run_wallet_clustering(self) -> int: ... # if this is a public method of the service

# Add other protocols as needed, e.g., for WalletAnalyzer, SmartMoneyClusterer, BehavioralScorer if VirtuosoGemFinder interacts with them directly beyond EnhancedScoring 